name: Dockerize your nodejs
on: 
  push: 
    branches: [main]
jobs:
  push_to_registry:
    name: build and push image to docker hub
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASS}}

      - name: Build and push docker image to docker hub
        uses: docker/build-push-action@v4
        with:
          context: ./
          push: true
          tags: 0645032/tests:latest
